config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index', as: :home_page
  resources :groups
  resources :contracts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :contract_groups, dependent: :destroy
  has_many :groups, through: :contract_groups

  validates :name, presence: true
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: %i[show edit update destroy]

  # GET /contracts or /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1 or /contracts/1.json
  def show; end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit; end

  # POST /contracts or /contracts.json
  def create
    @contract = Contract.new(contract_params.except(:groups))
    @contract.author = current_user

    if params[:contract][:groups].length <= 1
      flash.alert = 'Select atleast one checkbox'
      redirect_to new_contract_path and return
    end

    respond_to do |format|
      if @contract.save && create_or_delete_contracts_groups(@contract, params[:contract][:groups])
        format.html do
          redirect_to group_url(params[:contract][:groups][1]), notice: 'Contract was successfully created.'
        end
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1 or /contracts/1.json
  def update
    if params[:contract][:groups].length <= 1
      flash.alert = 'Select atleast one checkbox'
      redirect_to edit_contract_path and return
    end
    respond_to do |format|
      if @contract.update(contract_params.except(:groups)) && create_or_delete_contracts_groups(@contract,
                                                                                                params[:contract][:groups])
        format.html do
          redirect_to group_url(params[:contract][:groups][1]), notice: 'Contract was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1 or /contracts/1.json
  def destroy
    @contract.destroy

    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def create_or_delete_contracts_groups(contract, groups)
    contract.contract_groups.destroy_all
    groups.each do |group|
      ContractGroup.create(contract:, group: Group.find(group)) if group != ''
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_contract
    @contract = Contract.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contract_params
    params.require(:contract).permit(:name, :amount, groups: [])
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_contract.html.erb
<div id="<%= dom_id contract %>" class="p-2">
  <div class="border-top border-bottom w-80">
    <p class="m-0 mb-1"><%= contract.name %></p>
    <p class="m-0 text-muted"><i class="bi bi-archive"></i><%= contract.created_at %></p>
  </div>
  <p class="d-flex justify-content-between align-items-center m-0">TOTAL PAYMENT <strong>$<%=contract.amount %></strong></p>
</div>

app/views/contracts/_form.html.erb
<div class="container-fluid mt-3">
<%= form_with(model: contract) do |form| %>
  <% if contract.errors.any? %>
    <div style="color: red">
      <p><%= pluralize(contract.errors.count, "error") %> prohibited this contract from being saved:</p>

      <ul>
        <% contract.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating mb-3">
    <%= form.text_field :name,  class:"form-control", id:"floatingPassword", placeholder:"password" %>
    <%= form.label :name %>
  </div>

  <div class="form-floating mb-3">
    <%= form.number_field :amount, class:"form-control", id:"floatingPassword", placeholder:"password" %>
    <%= form.label :amount%>
  </div>
 <span class="check_box_validation" style="width:fit-content; color:red; margin:unset;"><%= alert %></span>
  <div>
     <%= form.label "Select category", style: "display: block"%>
    <%= form.collection_check_boxes :groups, group_list, :id, :name , required:true%>
  </div>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary mt-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Create transaction
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add transaction</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to Add this transaction?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= form.submit 'Add', class:"btn btn-primary"%>
      </div>
    </div>
  </div>
</div>
<% end %>
</div>

app/views/contracts/edit.html.erb
<h1>Editing contract</h1>

<%= render "form", contract: @contract %>

<br>

<div>
  <%= link_to "Show this contract", @contract %> |
  <%= link_to "Back to contracts", contracts_path %>
</div>

app/views/contracts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contracts</h1>

<div id="contracts">
  <% @contracts.each do |contract| %>
    <%= render contract %>
    <p>
      <%= link_to "Show this contract", contract %>
    </p>
  <% end %>
</div>

app/views/contracts/new.html.erb
<nav class="navbar navbar-expand-lg" style="background-color:#3778C2; color:#EDF5FE;">
<%= link_to groups_path, class:"link-light ms-4 fs-3", style:"text-decoration:none;" do%>
<i class="bi bi-arrow-left"></i>
<%end%>
<a class="navbar-brand w-50 me-5" href="#"  style="color:#EDF5FE;"><%='Add transaction'%></a>
</nav>

<%= render "form", contract: @contract %>

app/views/contracts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contract %>

<div>
  <%= link_to "Edit this contract", edit_contract_path(@contract) %> |
  <%= link_to "Back to contracts", contracts_path %>

  <%= button_to "Destroy this contract", @contract, method: :delete %>
</div>