config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index', as: :home_page
  resources :groups
  resources :contracts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
class Group < ApplicationRecord
  validate :acceptable_image
  validates :category_icon, attached: true
  validates :name, presence: true

  has_one_attached :category_icon
  has_many :contract_groups, dependent: :destroy
  has_many :contracts, through: :contract_groups
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_path, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :category_icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_card.html.erb
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-2 d-flex justify-content-between p-2">
    <div class="d-flex">
    <% if group.category_icon.attached?%>
   <image src="<%=(url_for(group.category_icon)) %>" class="img-fluid rounded-start" alt="Category image" style="max-width: 50px; height:50px;">
  <%end%>
  <div class="d-flex flex-column ms-2">
  <span class="card-text"><%= group.name %></span>
  <span class="card-text"><small class="text-muted"><%=group.created_at%></small></span>
  </div>
  </div>
  <h5 class="card-title">$<%=transaction_total(group)%></h5>
    </div>
  </div>
</div>

app/views/groups/_form.html.erb
<div class="container-fluid mt-3">
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <p><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</p>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating mb-3">
    <%= form.text_field :name,  class:"form-control", id:"floatingPassword" %>
    <%= form.label :name%>
  </div>

  <div class="mb-3">
  <%= form.label :category_icon, style:"display:block" %>
    <%= form.file_field :category_icon, id: "change-img-field", direct_upload: true%>
  </div>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Create Category
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add category</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to Add this category?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
         <%= form.submit 'Add', class:"btn btn-primary"%>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/groups/_group.html.erb
<div class="card mb-3 rounded-0 m-2" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-8 d-flex justify-content-between p-2">
    <div class="d-flex align-items-center">
    <% if group.category_icon.attached?%>
   <image src="<%=(url_for(group.category_icon)) %>" class="img-fluid rounded-start" alt="Category image" style="max-width: 50px; height:50px;">
  <%end%>
  <span class="card-text ms-1"><%= group.name %></span>
  </div>
    </div>
  </div>
  <p class="card-text ms-2  text-muted fs-6 ">This is fantastic. I've been following along the progress in fs-6 loem ipsomd lorem10 mndsfl jafbafpo ajdfhadpifjdapfhadfhdafdas</p>

  <%@group.contracts.order(created_at: :desc).each do |contract|%>
  <%= render contract %>
  <%end%>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div id="groups" class="position-relative z-index-1 p-3 pt-0">
<p style="color: green" ><%= notice %></p>
  <% @groups.each do |group| %>
      <%= link_to render(:partial => 'card', locals:{group:group}), group, class:"link-dark", style:"text-decoration:none;" %>
  <% end %>
</div>
<div class="position-fixed height start-50 translate-middle w-100 d-flex justify-content-center p-2 z-index-2" style="background-color:#60B524;">
<button type="button" class="btn btn-outline-light w-75 rounded-0"><%= link_to "Add category", new_group_path, class:"link-light link-with", style:"text-decoration:none;" %></button>
</div>

app/views/groups/new.html.erb
<nav class="navbar navbar-expand-lg" style="background-color:#3778C2; color:#EDF5FE;">
<%= link_to groups_path, class:"link-light ms-4 fs-3", style:"text-decoration:none;" do%>
<i class="bi bi-arrow-left"></i>
<%end%>
<a class="navbar-brand w-50 me-5" href="#"  style="color:#EDF5FE;"><%='Add category'%></a>
</nav>


<%= render "form", group: @group %>

app/views/groups/show.html.erb
<nav class="navbar navbar-expand-lg" style="background-color:#3778C2; color:#EDF5FE;">
<%= link_to groups_path, class:"link-light ms-4 fs-3", style:"text-decoration:none;" do%>
<i class="bi bi-arrow-left"></i>
<%end%>
<a class="navbar-brand w-50 me-5" href="#"  style="color:#EDF5FE;"><%='DETAILS'%></a>
</nav>
<div class="position-relative z-index-1>
<p style="color: green" class="m-0"><%= notice %></p>
<%= render :partial => 'group', locals:{group:@group}, class:"link-dark", style:"text-decoration:none;" %>

<div class="position-fixed height start-50 translate-middle w-100 d-flex justify-content-center p-2 z-index-2" style="background-color:#60B524;">
<button type="button" class="btn btn-outline-light w-75 rounded-0"><%= link_to "Add transaction", new_contract_path, class:"link-light link-with", style:"text-decoration:none;" %></button>
</div>
</div>